package com.conversant.webservice;

import javax.jws.WebService;

@WebService()
public interface Provision extends GenericWebService
{	
	public StandardResponse createDIDProduct(CreateDIDProductRequest createDIDProductRequest);
	public StandardResponse readDIDProduct(ReadDIDProductRequest readDIDProductRequest);
	public StandardResponse updateDIDProduct(UpdateDIDProductRequest updateDIDProductRequest);
	public StandardResponse deleteDIDProduct(DeleteDIDProductRequest deleteDIDProductRequest);
	
	public StandardResponse createSIPProduct(CreateSIPProductRequest createSIPProductRequest);
	public StandardResponse createVoicemailProduct(CreateVoicemailProductRequest createVoicemailProductRequest);
	
	public StandardResponse createDIDSubscription(CreateDIDSubscriptionRequest createDIDSubscriptionRequest);
	public StandardResponse createSIPSubscription(CreateSIPSubscriptionRequest createSIPSubscriptionRequest);
	public StandardResponse createVoicemailSubscription(CreateVoicemailSubscriptionRequest createVoicemailSubscriptionRequest);
	
	public StandardResponse createSubscriber(CreateSubscriberRequest createSubscriberRequest);
	public StandardResponse readSubscriber(ReadSubscriberRequest readSubscriberRequest);
	public StandardResponse updateSubscriber(UpdateSubscriberRequest updateSubscriberRequest);
	public StandardResponse deleteSubscriber(DeleteSubscriberRequest deleteSubscriberRequest);
	
	public StandardResponse createUserPreference(CreateUserPreferenceRequest createUserPreferenceRequest);
	public StandardResponse readUserPreference(ReadUserPreferenceRequest readUserPreferenceRequest);
	public StandardResponse updateUserPreferenceValue(UpdateUserPreferenceValueRequest updateUserPreferenceValueRequest);
	public StandardResponse updateUserPreferenceStartDate(UpdateUserPreferenceStartDateRequest updateUserPreferenceStartDateRequest);
	public StandardResponse updateUserPreferenceEndDate(UpdateUserPreferenceEndDateRequest updateUserPreferenceEndDateRequest);
	public StandardResponse deleteUserPreference(DeleteUserPreferenceRequest deleteUserPreferenceRequest);
	
	public StandardResponse createVoicemailUser(CreateVoicemailUserRequest createVoicemailUserRequest);
	public StandardResponse deleteVoicemailUser(DeleteVoicemailUserRequest deleteVoicemailUserRequest);
	
	public StandardResponse createVoicemailUserPreferences(CreateVoicemailUserPreferencesRequest createVoicemailUserPreferencesRequest);
	public StandardResponse deleteVoicemailUserPreferences(DeleteVoicemailUserPreferencesRequest deleteVoicemailUserPreferencesRequest);
	
	public StandardResponse createVoicemailDialPlan(CreateVoicemailDialPlanRequest createVoicemailDialPlanRequest);
	public StandardResponse deleteVoicemailDialPlan(DeleteVoicemailDialPlanRequest deleteVoicemailDialPlanRequest);
	
	public StandardResponse validateProvisionDIDParameters(ValidateProvisionDIDParametersRequest validateProvisionDIDParametersRequest);
	
	public StandardResponse createCallProduct(CreateCallProductRequest createCallProductRequest);
	public StandardResponse createCallSubscription(CreateCallSubscriptionRequest createCallSubscriptionRequest);
	
	public ReadRadiusAccountsResponse readRadiusAccountsByInvoice(ReadRadiusAccountsByInvoiceRequest readRadiusAccountsByInvoiceRequest);
	
	public StandardResponse createNumberPortSubscription(CreateNumberPortSubscriptionRequest createNumberPortSubscriptionRequest);
	
	public ReadRadiusAccountsResponse readRadiusAccountsSearch(ReadRadiusAccountsSearchRequest readRadiusAccountsSearchRequest);
	
	public StandardResponse endDIDSubscription(EndDIDSubscriptionRequest endDIDSubscriptionRequest);
	public StandardResponse endSIPSubscription(EndSIPSubscriptionRequest endSIPSubscriptionRequest);
	public StandardResponse endVoicemailSubscription(EndVoicemailSubscriptionRequest endVoicemailSubscriptionRequest);
	public StandardResponse endCallSubscription(EndCallSubscriptionRequest endCallSubscriptionRequest);
	
	public StandardResponse endVoicemailUserPreferences(EndVoicemailUserPreferencesRequest endVoicemailUserPreferencesRequest);
	
	public StandardResponse createCvoxUser(CreateCvoxUserRequest createCvoxUserRequest);
	public StandardResponse updateCvoxUser(UpdateCvoxUserRequest updateCvoxUserRequest);
}
